--  Configuration for test_z85padded_01 generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Test_Z85padded_01_Config is
   pragma Pure;

   Crate_Version : constant String := "0.0.1-dev";
   Crate_Name : constant String := "test_z85padded_01";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "ubuntu";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

end Test_Z85padded_01_Config;
