/* Configuration for test_z85padded_01 generated by Alire */
#ifndef TEST_Z85PADDED_01_CONFIG_H
#define TEST_Z85PADDED_01_CONFIG_H

#define CRATE_VERSION "0.0.1-dev"
#define CRATE_NAME "test_z85padded_01"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "ubuntu"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
